apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 2  # El ejercicio pide probar escalado
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: rdmon14/todo-broadcaster:v1
          env:
            - name: NATS_URL
              value: "nats://my-nats.default.svc.cluster.local:4222"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-config
                  key: token
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-config
                  key: chatid