apiVersion: v1
kind: Service
metadata:
  name: my-nats
  namespace: default
spec:
  selector:
    app: my-nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nats
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nats
  template:
    metadata:
      labels:
        app: my-nats
    spec:
      containers:
      - name: nats
        image: nats:alpine
        ports:
        - containerPort: 4222