apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-pvc
  namespace: project
spec:
  storageClassName: standard # Clase por defecto en GKE para discos SSD/Standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi