apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  strategy:
    type: Recreate # <--- Esto evita el bloqueo del disco
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-image-pvc
      containers:
        - name: todo-frontend
          image: todo-frontend-image # Placeholder para Kustomize
          env:
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: FRONTEND_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: BACKEND_URL
            - name: IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_PATH
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
          ports:
            - containerPort: 3000