apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  # Esto se montará como un archivo llamado information.txt
  information.txt: |
    this text is from file
  # Esto se inyectará como la variable de entorno MESSAGE
  MESSAGE: "hello world"