apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: NodePort # Requerido para Ingress en GKE
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 3000