apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises 
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # El puerto de tu app