apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-image-pvc
      containers:
        - name: todo-app
          image: rdmon14/todo-app:v33
          env:
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: FRONTEND_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: BACKEND_URL
            - name: IMAGE_PATH # <--- Inyectando la ruta del archivo
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_PATH
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files