apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress # Usamos el mismo nombre que ya tienes
spec:
  rules:
  - http:
      paths:
      # RUTA 1: Log Output (Ejercicio 1.7/1.9)
      # Ahora este es el dueño de la raíz "/"
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port:
              number: 80

      # RUTA 2: Ping-Pong (Ejercicio 1.9)
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-svc
            port:
              number: 80

      # RUTA 3: Tu Todo App (Ejercicio 1.8)
      # La movemos a "/app" para que no choque con la raíz
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 80