apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: project
  annotations:
    # Si usas Traefik (k3d), esto ayuda con los prefijos
    traefik.ingress.kubernetes.io/router.middlewares: project-strip-app-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: todo-app-svc
            port:
              number: 80