apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-pvc
spec:
  storageClassName: local-storage # El mismo que usaste en el 1.11
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi