apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app # This is the app as declared in the deployment.
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080 # El puerto de tu app de Node.js