apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 80          # El puerto que usa el Ingress
      targetPort: 3000  # El puerto real de tu app Node.js